module Types
  class MutationType < Types::BaseObject
    # TODO: remove the test_field code as it is generated by rails engine
    field :test_field, String, null: false,
      description: "An example field added by the generator"
    def test_field
      "Hello World"
    end

    field :create_business, BusinessType, null: true, description: "Create a business" do
      argument :business, Types::BusinessInputType, required: true
    end

    def create_business(business:)
      Entities::Business.create business.to_h
    end

    field :create_applicant, ApplicantType, null: true, description: "Create a business" do
      argument :applicant, Types::ApplicantInputType, required: true
    end

    def create_applicant(applicant:)
      Individual::Applicant.create applicant.to_h
    end
  end
end
